<?php

namespace App\Console\Commands;

use App\Models\Tenant;
use App\Models\User;
use App\Support\CustomerMembership;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;

class UserCreate extends Command
{
    protected $signature = 'user:create
        {email : Login email, must be unique}
        {--first-name=Admin : First name}
        {--last-name=User : Last name}
        {--password= : Leave empty to auto-generate}
        {--role=User : Customer-scoped role to assign (Admin, Editor, User). Requires --customer.}
        {--customer= : Customer slug to attach the user to with the given role}
        {--super-admin : Flag the user as a platform SuperAdmin}
        {--verified : Mark email as verified immediately}';

    protected $description = 'Create a user from the CLI (useful when the web flow is unavailable).';

    public function handle(): int
    {
        $email = (string) $this->argument('email');

        if (User::where('email', $email)->exists()) {
            $this->error("A user with email {$email} already exists.");

            return self::FAILURE;
        }

        $customer = null;
        $customerSlug = $this->option('customer');
        if ($customerSlug !== null && $customerSlug !== '') {
            $customer = Tenant::query()->where('slug', $customerSlug)->first();
            if ($customer === null) {
                $this->error("Customer with slug [{$customerSlug}] not found.");

                return self::FAILURE;
            }
        }

        // `--password=` (empty) must be treated as "unset" too, or we'd hash
        // an empty string and create an account with a blank password.
        $provided = $this->option('password');
        $autoGenerated = $provided === null || $provided === '';
        $password = $autoGenerated ? bin2hex(random_bytes(16)) : (string) $provided;

        $user = new User;
        $user->forceFill([
            'first_name' => (string) $this->option('first-name'),
            'last_name' => (string) $this->option('last-name'),
            'email' => $email,
            'password' => Hash::make($password),
            'email_verified_at' => $this->option('verified') ? now() : null,
            'is_super_admin' => (bool) $this->option('super-admin'),
        ])->save();

        if ($customer !== null) {
            CustomerMembership::attach($user, $customer, (string) $this->option('role'));
            $this->info("Created user {$user->id} <{$email}> as {$this->option('role')} on [{$customer->slug}].");
        } else {
            $this->info("Created user {$user->id} <{$email}>.");
        }

        if ($autoGenerated) {
            $this->warn("Temporary password: {$password}");
            $this->warn('Share it securely. The user should change it immediately after first login.');
        }

        return self::SUCCESS;
    }
}
